/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports all enum related types from the schema.
 *
 * 🟢 You can import this file directly.
 */

export const SessionType = {
  WEEKLY: 'WEEKLY',
  SPECIAL: 'SPECIAL',
} as const;

export type SessionType = (typeof SessionType)[keyof typeof SessionType];

export const ReactionType = {
  LIKE: 'LIKE',
  HEART: 'HEART',
} as const;

export type ReactionType = (typeof ReactionType)[keyof typeof ReactionType];

export const AccountRole = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
} as const;

export type AccountRole = (typeof AccountRole)[keyof typeof AccountRole];

export const AccountStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  DISABLED: 'DISABLED',
  DELETED: 'DELETED',
} as const;

export type AccountStatus = (typeof AccountStatus)[keyof typeof AccountStatus];

export const SchoolPlan = {
  FREE: 'FREE',
  PRO: 'PRO',
  ENTERPRISE: 'ENTERPRISE',
} as const;

export type SchoolPlan = (typeof SchoolPlan)[keyof typeof SchoolPlan];

export const SchoolStatus = {
  ACTIVE: 'ACTIVE',
  PENDING: 'PENDING',
  SUSPENDED: 'SUSPENDED',
  DELETED: 'DELETED',
} as const;

export type SchoolStatus = (typeof SchoolStatus)[keyof typeof SchoolStatus];

export const UserStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  DISABLED: 'DISABLED',
  DELETED: 'DELETED',
} as const;

export type UserStatus = (typeof UserStatus)[keyof typeof UserStatus];

export const UserRole = {
  DIRECTOR: 'DIRECTOR',
  MANAGER: 'MANAGER',
  TEACHER: 'TEACHER',
  PARENT: 'PARENT',
  NURSE: 'NURSE',
  DRIVER: 'DRIVER',
} as const;

export type UserRole = (typeof UserRole)[keyof typeof UserRole];

export const ClassGrade = {
  KG: 'KG',
  ONE: 'ONE',
  TWO: 'TWO',
  THREE: 'THREE',
  FOUR: 'FOUR',
  FIVE: 'FIVE',
  SIX: 'SIX',
} as const;

export type ClassGrade = (typeof ClassGrade)[keyof typeof ClassGrade];

export const FeeItemStatus = {
  PAID: 'PAID',
  UNPAID: 'UNPAID',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
} as const;

export type FeeItemStatus = (typeof FeeItemStatus)[keyof typeof FeeItemStatus];

export const MediaStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  DELETED: 'DELETED',
  FAILED: 'FAILED',
} as const;

export type MediaStatus = (typeof MediaStatus)[keyof typeof MediaStatus];

export const MediaType = {
  IMAGE: 'IMAGE',
  VIDEO: 'VIDEO',
  DOCUMENT: 'DOCUMENT',
} as const;

export type MediaType = (typeof MediaType)[keyof typeof MediaType];

export const NotificationScheduleType = {
  IMMEDIATE: 'IMMEDIATE',
  SCHEDULED: 'SCHEDULED',
  DELAYED: 'DELAYED',
} as const;

export type NotificationScheduleType = (typeof NotificationScheduleType)[keyof typeof NotificationScheduleType];

export const NotificationLanguage = {
  en: 'en',
  ar: 'ar',
  fr: 'fr',
} as const;

export type NotificationLanguage = (typeof NotificationLanguage)[keyof typeof NotificationLanguage];

export const NotificationType = {
  GLOBAL: 'GLOBAL',
  GROUP: 'GROUP',
  PRIVATE: 'PRIVATE',
} as const;

export type NotificationType = (typeof NotificationType)[keyof typeof NotificationType];

export const NotificationContentType = {
  TEACHER_COMMENT: 'TEACHER_COMMENT',
  FEED: 'FEED',
} as const;

export type NotificationContentType = (typeof NotificationContentType)[keyof typeof NotificationContentType];

export const Gender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
} as const;

export type Gender = (typeof Gender)[keyof typeof Gender];

export const DayOfWeek = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const;

export type DayOfWeek = (typeof DayOfWeek)[keyof typeof DayOfWeek];

export const StudentStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
  EXPELLED: 'EXPELLED',
} as const;

export type StudentStatus = (typeof StudentStatus)[keyof typeof StudentStatus];

export const Semester = {
  FIRST: 'FIRST',
  SECOND: 'SECOND',
  THIRD: 'THIRD',
} as const;

export type Semester = (typeof Semester)[keyof typeof Semester];

export const SubjectDomain = {
  ARABIC_LANGUAGE: 'ARABIC_LANGUAGE',
  SCIENCE_TECHNOLOGY: 'SCIENCE_TECHNOLOGY',
  SOCIAL_EDUCATION: 'SOCIAL_EDUCATION',
  ART_EDUCATION: 'ART_EDUCATION',
  PHYSICAL_EDUCATION: 'PHYSICAL_EDUCATION',
  FRENCH_LANGUAGE: 'FRENCH_LANGUAGE',
  ENGLISH_LANGUAGE: 'ENGLISH_LANGUAGE',
} as const;

export type SubjectDomain = (typeof SubjectDomain)[keyof typeof SubjectDomain];

export const AttendanceStatus = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  LATE: 'LATE',
  EXCUSED: 'EXCUSED',
} as const;

export type AttendanceStatus = (typeof AttendanceStatus)[keyof typeof AttendanceStatus];
