@apiKey = AIzaSyBoFeoCUvczJXVp2FhWYm26UiSGjmYLqOo
@firebaseUrl = https://identitytoolkit.googleapis.com/v1


@baseUrl = http://localhost:10000/api

@ManagerEmail = manager1@fake.com
@ManagerPassword = 12345678



########################################
# AUTH FLOW: ADMIN LOGIN
########################################

### 
# @name firebase_login
POST {{firebaseUrl}}/accounts:signInWithPassword?key={{apiKey}}
Content-Type: application/json

{
  "email": "{{ManagerEmail}}",
  "password": "{{ManagerPassword}}",
  "returnSecureToken": true
}



###
# @name serverLogin
POST {{baseUrl}}/auth/password
Content-Type: application/json

{
    "token": "{{firebase_login.response.body.idToken}}"
}

###
@schoolId = {{serverLogin.response.body.data.administration[0].school.id}}

###
# @name createExtraCurricular
POST {{baseUrl}}/schools/{{schoolId}}/extra-curriculars
Content-Type: application/json
Authorization: Bearer {{firebase_login.response.body.idToken}}

{
    "title": {
        "en": "Curricular rest",
        "fr": "Curricular rest",
        "ar": "Curricular rest"
    },
    "grade": "SIX",
    "dayOfWeek": "MONDAY",
    "startTime": "08:00",
    "endTime": "09:00",
    "teacherId": null
}


###
# @name updateExtraCurricular
PUT {{baseUrl}}/schools/{{schoolId}}/extra-curriculars/{{createExtraCurricular.response.body.data.id}}
Content-Type: application/json
Authorization: Bearer {{firebase_login.response.body.idToken}}

{
    "title": {
        "en": "Curricular rest updated",
        "fr": "Curricular rest updated",
        "ar": "Curricular rest updated"
    },
    "grade": "SEVEN",
    "dayOfWeek": "TUESDAY",
    "startTime": "09:00",
    "endTime": "10:00",
    "teacherId": null
}

###
# @name findOne
GET {{baseUrl}}/schools/{{schoolId}}/extra-curriculars/{{createExtraCurricular.response.body.data.id}}
Content-Type: application/json
Authorization: Bearer {{firebase_login.response.body.idToken}}


###
# @name deleteExtraCurricular
DELETE {{baseUrl}}/schools/{{schoolId}}/extra-curriculars/{{createExtraCurricular.response.body.data.id}}
Content-Type: application/json
Authorization: Bearer {{firebase_login.response.body.idToken}}


###
# @name findAllExtraCurricular
GET {{baseUrl}}/schools/{{schoolId}}/extra-curriculars?page=1&size=10
Content-Type: application/json
Authorization: Bearer {{firebase_login.response.body.idToken}}


###
@extraCurricularId = {{findAllExtraCurricular.response.body.data[0].id}}


###
# @name getExtraCurricularStudents
GET {{baseUrl}}/schools/{{schoolId}}/extra-curriculars/{{extraCurricularId}}/students
Content-Type: application/json
Authorization: Bearer {{firebase_login.response.body.idToken}}
 