@apiKey = AIzaSyBoFeoCUvczJXVp2FhWYm26UiSGjmYLqOo
@firebaseUrl = https://identitytoolkit.googleapis.com/v1


@baseUrl = http://localhost:10000/api


@ManagerEmail = manager1@fake.com
@ManagerPassword = 12345678


########################################
# AUTH FLOW: ADMIN LOGIN
########################################

### 
# @name firebase_login
POST {{firebaseUrl}}/accounts:signInWithPassword?key={{apiKey}}
Content-Type: application/json

{
  "email": "{{ManagerEmail}}",
  "password": "{{ManagerPassword}}",
  "returnSecureToken": true
}



###
# @name serverLogin
POST {{baseUrl}}/auth/password
Content-Type: application/json

{
    "token": "{{firebase_login.response.body.idToken}}"
}

###
@schoolId = {{serverLogin.response.body.administration[0].school.id}}



#####################################
#####################################
#####################################


###
# @name getAttendance
GET {{baseUrl}}/schools/{{schoolId}}/students/296f6611-1d36-54ad-adab-fec236540239/attendances
Content-Type: application/json
Authorization: Bearer {{firebase_login.response.body.idToken}}


###
# @name getFees
GET {{baseUrl}}/schools/{{schoolId}}/students/296f6611-1d36-54ad-adab-fec236540239/fees
Content-Type: application/json
Authorization: Bearer {{firebase_login.response.body.idToken}}


###
# @name getComments
GET {{baseUrl}}/schools/{{schoolId}}/students/296f6611-1d36-54ad-adab-fec236540239/teacher-comments
Content-Type: application/json
Authorization: Bearer {{firebase_login.response.body.idToken}}



