@apiKey = AIzaSyBoFeoCUvczJXVp2FhWYm26UiSGjmYLqOo
@firebaseUrl = https://identitytoolkit.googleapis.com/v1


@baseUrl = http://localhost:10000/api


@TeacherEmail = teacher1@fake.com
@TeacherPassword = 12345678




### 
# @name firebase_login
POST {{firebaseUrl}}/accounts:signInWithPassword?key={{apiKey}}
Content-Type: application/json

{
  "email": "{{TeacherEmail}}",
  "password": "{{TeacherPassword}}",
  "returnSecureToken": true
}


###
# @name serverLogin
POST {{baseUrl}}/auth/password
Content-Type: application/json

{
    "token": "{{firebase_login.response.body.idToken}}"
}

###
@TeacherId = {{serverLogin.response.body.data.teacher[0].id}}
@SchoolId = {{serverLogin.response.body.data.teacher[0].school.id}}
@UserId = {{serverLogin.response.body.data.teacher[0].userId}}


###
# @name getMe
GET {{baseUrl}}/auth/me
Content-Type: application/json
Authorization: Bearer {{firebase_login.response.body.idToken}}


###
# @name updateTeacher
PUT {{baseUrl}}/schools/{{getMe.response.body.teacher[0].school.id}}/teachers/{{getMe.response.body.teacher[0].id}}
Content-Type: application/json
Authorization: Bearer {{firebase_login.response.body.idToken}}

{
  "firstName": "John Profile",
  "lastName": "Doe Profile",
  "gender": "MALE",
  "dateOfBirth": "1995-05-15",
  "phone": "55123522",
  "cin": "12345679",
  "address": "123 Main Street, Springfield",
  "avatarId": null
}


###
# @name getTimetable
GET {{baseUrl}}/schools/{{SchoolId}}/teachers/{{TeacherId}}/timetable?day=MONDAY
Content-Type: application/json
Authorization: Bearer {{firebase_login.response.body.idToken}}


###
# @name getExtraCurricularWithSession
GET {{baseUrl}}/schools/{{SchoolId}}/teachers/{{TeacherId}}/extraCurriculars
Content-Type: application/json
Authorization: Bearer {{firebase_login.response.body.idToken}}


###
# @name getClassrooms
GET {{baseUrl}}/schools/{{SchoolId}}/teachers/{{TeacherId}}/classrooms
Content-Type: application/json
Authorization: Bearer {{firebase_login.response.body.idToken}}

 

###
# @name addHomework
POST {{baseUrl}}/schools/{{SchoolId}}/homework
Content-Type: application/json
Authorization: Bearer {{firebase_login.response.body.idToken}}

{
    "title": "Homework 1",
    "content": "Homework 1 content",
    "due": "2022-01-01",
    "type": "STANDARD",
    "files":   ["f214dea5-8b07-480c-8cba-89ea09797ce2"],
    "details": [
        {
            "due": "2022-01-01",
            "assignmentId": "33ad73b3-e6b6-4b0a-a589-46304f24c23d",
            "studentIds": []
            
        }
    ]
}




###
# @name sendMessage
POST {{baseUrl}}/schools/{{SchoolId}}/homework/{{addHomework.response.body.data[0].id}}/messages
Content-Type: application/json
Authorization: Bearer {{firebase_login.response.body.idToken}}

{
    "content": "yes plz "
}


###
# @name getHistory
GET {{baseUrl}}/schools/{{SchoolId}}/homework/{{addHomework.response.body.data[0].id}}/messages/
Content-Type: application/json
Authorization: Bearer {{firebase_login.response.body.idToken}}